services:
  - type: web
    name: hr-agent-bot
    env: docker
    plan: free
    branch: main
    repo: https://github.com/karisnidevibalan/deploy-hr-agent-bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    autoDeploy: true
